spring:
    profiles:
        active: local
    application:
        name: Plaza's Microservice

app:
    name: Plaza's Microservice
    version: 0.0.1
    description: Microservice for managing restaurants, menus and orders